<a href="https://colab.research.google.com/github/Mar-SHieee/Filtering/blob/main/Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Data Understanding**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/global_ecommerce_sales.csv')

In [ ]:
df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

In [ ]:
df.tail()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
1995,ORD-10823,2025-12-31,Linda Nilsson,Consumer,France,Europe,Furniture,Folding Table Portable,5,104.73,0,523.65,19.10,190.36,PayPal
1996,ORD-10896,2025-12-31,Ayumi Dubois,Consumer,France,Europe,Clothing & Accessories,Cotton Formal Shirt,11,59.27,5,619.37,20.94,272.44,PayPal
1997,ORD-11148,2025-12-31,Barbara Jones,Consumer,Spain,Europe,Technology,Webcam HD 1080p,6,31.79,15,162.13,15.19,42.03,Bank Transfer
1998,ORD-11519,2025-12-31,Maria Suzuki,Home Office,Spain,Europe,Clothing & Accessories,Sports Water Bottle 750ml,5,9.50,5,45.12,14.25,7.12,Credit Card
1999,ORD-11701,2025-12-31,Susan Russo,Home Office,South Korea,Asia Pacific,Clothing & Accessories,Sports Water Bottle 750ml,11,28.27,0,310.97,36.23,119.26,Credit Card

In [ ]:
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Customer_Segment',
       'Country', 'Region', 'Product_Category', 'Product_Name', 'Quantity',
       'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Shipping_Cost',
       'Profit', 'Payment_Method'],
      dtype='object')

In [ ]:
df.shape

(2000, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2000 non-null   object
 1   Order_Date        2000 non-null   object
 2   Customer_Name     2000 non-null   object
 3   Customer_Segment  2000 non-null   object
 4   Country           2000 non-null   object
 5   Region            2000 non-null   object
 6   Product_Category  2000 non-null   object
 7   Product_Name      2000 non-null   object
 8   Quantity          2000 non-null   int64
 9   Unit_Price        2000 non-null   float64
 10  Discount_Percent  2000 non-null   int64
 11  Total_Sales       2000 non-null   float64
 12  Shipping_Cost     2000 non-null   float64
 13  Profit            2000 non-null   float64
 14  Payment_Method    2000 non-null   object
dtypes: float64(4), int64(2), object(9)
memory usage: 234.5+ KB

In [ ]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Name       0
Customer_Segment    0
Country             0
Region              0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Shipping_Cost       0
Profit              0
Payment_Method      0
dtype: int64

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
df.describe()

,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000
mean,3.557500,73.329490,8.572500,242.279670,12.90212,79.436160
std,2.704506,79.311014,7.261274,382.583802,5.22319,137.573593
min,1.000000,3.030000,0.000000,2.420000,5.52000,-11.280000
25%,2.000000,18.757500,0.000000,41.227500,9.45750,6.865000
50%,3.000000,46.420000,10.000000,113.125000,11.84500,32.830000
75%,5.000000,90.250000,15.000000,266.552500,14.92000,90.297500
max,15.000000,472.560000,30.000000,3813.980000,40.44000,1373.630000

##**Selection & Filtering**

In [ ]:
df[["Product_Name", "Product_Category" , "Quantity", "Unit_Price", "Profit"]]

,Product_Name,Product_Category,Quantity,Unit_Price,Profit
0,Wireless Bluetooth Headphones,Technology,3,99.43,124.92
1,Mechanical Gaming Keyboard,Technology,4,97.93,83.62
2,Binder Clips Assorted 48pc,Office Supplies,2,10.74,3.69
3,Webcam HD 1080p,Technology,2,61.86,26.32
4,Standing Desk Converter,Furniture,4,330.67,253.44
...,...,...,...,...,...
1995,Folding Table Portable,Furniture,5,104.73,190.36
1996,Cotton Formal Shirt,Clothing & Accessories,11,59.27,272.44
1997,Webcam HD 1080p,Technology,6,31.79,42.03
1998,Sports Water Bottle 750ml,Clothing & Accessories,5,9.50,7.12
1999,Sports Water Bottle 750ml,Clothing & Accessories,11,28.27,119.26

In [ ]:
df[df["Quantity"] > 2]

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card
11,ORD-11499,2023-01-08,Kenji Rossi,Corporate,Spain,Europe,Office Supplies,Paper Clips Box 500pc,3,7.80,10,21.06,12.61,-2.08,Cash on Delivery
15,ORD-11330,2023-01-13,Marco Moreau,Corporate,Japan,Asia Pacific,Clothing & Accessories,Business Casual Blazer,3,51.92,30,109.03,13.39,17.76,PayPal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD-10823,2025-12-31,Linda Nilsson,Consumer,France,Europe,Furniture,Folding Table Portable,5,104.73,0,523.65,19.10,190.36,PayPal
1996,ORD-10896,2025-12-31,Ayumi Dubois,Consumer,France,Europe,Clothing & Accessories,Cotton Formal Shirt,11,59.27,5,619.37,20.94,272.44,PayPal
1997,ORD-11148,2025-12-31,Barbara Jones,Consumer,Spain,Europe,Technology,Webcam HD 1080p,6,31.79,15,162.13,15.19,42.03,Bank Transfer
1998,ORD-11519,2025-12-31,Maria Suzuki,Home Office,Spain,Europe,Clothing & Accessories,Sports Water Bottle 750ml,5,9.50,5,45.12,14.25,7.12,Credit Card
1999,ORD-11701,2025-12-31,Susan Russo,Home Office,South Korea,Asia Pacific,Clothing & Accessories,Sports Water Bottle 750ml,11,28.27,0,310.97,36.23,119.26,Credit Card

In [ ]:
df["Product_Category"].value_counts()

Product_Category
Technology                567
Office Supplies           513
Furniture                 507
Clothing & Accessories    413
Name: count, dtype: int64

In [ ]:
df[( df["Product_Category"] == "Technology" ) & (df["Profit"] > 100 )]

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
27,ORD-10589,2023-01-20,Mary Davis,Consumer,Argentina,South America,Technology,Portable External SSD 1TB,4,121.25,0,485.00,18.53,199.72,PayPal
54,ORD-11760,2023-02-04,Sakura Thomas,Corporate,Argentina,South America,Technology,Webcam HD 1080p,7,79.23,15,471.42,19.84,146.54,Cash on Delivery
58,ORD-11503,2023-02-07,Felix Yamamoto,Consumer,Japan,Asia Pacific,Technology,Noise Cancelling Earbuds,2,173.37,0,346.74,10.89,145.14,PayPal
67,ORD-11270,2023-02-10,Isabella White,Consumer,Germany,Europe,Technology,Portable External SSD 1TB,9,111.98,5,957.43,24.38,378.75,Credit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,ORD-11102,2025-11-17,William Sato,Corporate,Italy,Europe,Technology,Wireless Ergonomic Mouse,7,41.83,5,278.17,10.79,106.33,PayPal
1911,ORD-10303,2025-11-18,Diego Williams,Consumer,India,Asia Pacific,Technology,Laptop Stand Adjustable,9,34.21,5,292.50,13.63,109.53,Credit Card
1934,ORD-11172,2025-11-29,Kenji Wang,Consumer,China,Asia Pacific,Technology,Tablet Stand Holder,13,31.37,10,367.03,38.63,104.10,Cash on Delivery
1952,ORD-11374,2025-12-07,Robert Martinez,Consumer,Canada,North America,Technology,Wireless Bluetooth Headphones,4,128.26,20,410.43,9.52,118.74,Cash on Delivery
1972,ORD-10186,2025-12-17,Sophie Khan,Consumer,Nigeria,Middle East & Africa,Technology,Noise Cancelling Earbuds,5,68.79,0,343.95,20.77,134.01,Cash on Delivery

In [ ]:
df["Region"].value_counts()

Region
North America           578
Asia Pacific            520
Europe                  503
Middle East & Africa    208
South America           191
Name: count, dtype: int64

In [ ]:
print(df.loc[ df["Region"] == "North America", "Total_Sales"].sum())

133876.38

In [ ]:
print(df.loc[ df["Region"] == "North America", "Profit"].sum())

45250.090000000004

In [ ]:
df.loc[df["Region"] == "North America", 'Product_Category'].mode()

0    Office Supplies
Name: Product_Category, dtype: object

In [ ]:
top_profit = df.sort_values("Profit", ascending=False)

In [ ]:
top_profit.iloc[:10, [0, 5, 7, 11, 13]]

       Order_ID         Region             Product_Name  Total_Sales   Profit
277   ORD-11665         Europe     Corner L-Shaped Desk      3783.56  1373.63
133   ORD-11090   Asia Pacific     Corner L-Shaped Desk      3813.98  1370.08
742   ORD-10413  North America   Ergonomic Office Chair      3007.62  1189.79
1020  ORD-11153         Europe     Mesh Back Task Chair      3094.04  1116.45
85    ORD-11624  North America   Ergonomic Office Chair      2835.36  1115.05
990   ORD-11706         Europe   Ergonomic Office Chair      2901.11  1054.26
905   ORD-10359  North America     Corner L-Shaped Desk      2620.28  1017.49
1303  ORD-11242  North America     Mesh Back Task Chair      2538.50   992.84
505   ORD-11091         Europe  Standing Desk Converter      2701.31   874.37
1788  ORD-10536         Europe  Standing Desk Converter      2180.22   860.28

In [ ]:
df.loc[ (df["Region"] == "Europe") & (df["Profit"] > 1000 ), ["Product_Category", "Profit", "Total_Sales"]]

     Product_Category   Profit  Total_Sales
277         Furniture  1373.63      3783.56
990         Furniture  1054.26      2901.11
1020        Furniture  1116.45      3094.04

##**Feature Engineering**

In [ ]:
df["Gross_Sales"] = df["Unit_Price"] * df["Quantity"]

In [ ]:
df["Gross_Sales"]

0        298.29
1        391.72
2         21.48
3        123.72
4       1322.68
         ...
1995     523.65
1996     651.97
1997     190.74
1998      47.50
1999     310.97
Name: Gross_Sales, Length: 2000, dtype: float64

In [ ]:
df["Net_Sales"] = df["Gross_Sales"] * (1 - df["Discount_Percent"] / 100)

In [ ]:
df["Net_Sales"]

0        298.2900
1        313.3760
2         21.4800
3        105.1620
4       1058.1440
          ...
1995     523.6500
1996     619.3715
1997     162.1290
1998      45.1250
1999     310.9700
Name: Net_Sales, Length: 2000, dtype: float64

In [ ]:
df["Total_Sales"]

0        298.29
1        313.38
2         21.48
3        105.16
4       1058.14
         ...
1995     523.65
1996     619.37
1997     162.13
1998      45.12
1999     310.97
Name: Total_Sales, Length: 2000, dtype: float64

###**Actually Net_Sales & Total_Sales are the same.**

In [ ]:
df["Profit_Margin"] = (df["Profit"] / df["Net_Sales"]) * 100

In [ ]:
df["Profit_Margin"]

0       41.878709
1       26.683601
2       17.178771
3       25.028052
4       23.951371
          ...
1995    36.352526
1996    43.986525
1997    25.923801
1998    15.778393
1999    38.350966
Name: Profit_Margin, Length: 2000, dtype: float64

In [ ]:
df["Profit"]

0       124.92
1        83.62
2         3.69
3        26.32
4       253.44
         ...
1995    190.36
1996    272.44
1997     42.03
1998      7.12
1999    119.26
Name: Profit, Length: 2000, dtype: float64

In [ ]:
df[["Gross_Sales", "Net_Sales", "Profit_Margin"]] = ( df[["Gross_Sales", "Net_Sales", "Profit_Margin"]].round(2))

In [ ]:
df[["Gross_Sales", "Net_Sales", "Profit_Margin"]].head()

   Gross_Sales  Net_Sales  Profit_Margin
0       298.29     298.29          41.88
1       391.72     313.38          26.68
2        21.48      21.48          17.18
3       123.72     105.16          25.03
4      1322.68    1058.14          23.95

## **Grouping and Aggregation**

In [ ]:
categories = (df.groupby("Product_Category")[["Total_Sales", "Profit"]].sum().sort_values(by="Profit", ascending=False))

In [ ]:
categories

                        Total_Sales    Profit
Product_Category
Furniture                 256274.68  81171.57
Technology                139518.22  48268.65
Clothing & Accessories     69375.63  26112.94
Office Supplies            19390.81   3319.16

##**Best Category : Furniture**

In [ ]:
best_category = (
    df.groupby("Product_Category")["Profit"]
      .sum()
      .idxmax()
)

best_category

'Furniture'

In [ ]:
regions = (df.groupby("Region")[["Total_Sales", "Profit"]].sum().sort_values(by="Profit", ascending=False))

In [ ]:
regions

                      Total_Sales    Profit
Region
Europe                  137006.20  45672.16
North America           133876.38  45250.09
Asia Pacific            121707.51  39116.61
South America            46051.13  14680.98
Middle East & Africa     45918.12  14152.48

##**Strongest Region : Europe**

In [ ]:
strongest_region = (
    df.groupby("Region")["Profit"]
      .sum()
      .idxmax()
)

strongest_region

'Europe'

In [ ]:
Product_Name = (df.groupby("Product_Name")[["Total_Sales", "Profit"]].sum().sort_values(by="Profit", ascending=False))

In [ ]:
Product_Name

                                Total_Sales    Profit
Product_Name
Ergonomic Office Chair             45405.15  15104.58
Standing Desk Converter            46614.22  14694.35
Corner L-Shaped Desk               41070.48  13663.00
Mesh Back Task Chair               38179.77  12820.11
Wireless Bluetooth Headphones      28258.70  10611.08
Mechanical Gaming Keyboard         24072.42   8381.19
Filing Cabinet 3-Drawer            23108.01   7041.80
Portable External SSD 1TB          18065.30   6556.75
Business Casual Blazer             14327.72   6004.33
Noise Cancelling Earbuds           16119.60   5973.01
Folding Table Portable             18663.13   5589.03
Bookshelf 5-Tier                   17741.59   5490.57
Travel Backpack 30L                11204.23   4299.81
Webcam HD 1080p                    11637.33   3910.34
Floating Wall Shelves Set          11767.30   3407.42
Smart LED Desk Lamp                10143.78   3289.21
Wireless Ergonomic Mouse            9995.39   3190.96
Polarized Sunglasses                8454.43   3176.54
Laptop Stand Adjustable             9558.20   3174.20
Cotton Formal Shirt                 8306.97   3160.35
Canvas Messenger Bag                6545.19   2455.64
Leather Wallet Minimalist           5811.31   2181.81
Monitor Riser Wood                  8131.41   2010.94
Leather Belt Classic                5231.35   1836.80
USB-C Hub Multiport Adapter         5605.73   1670.54
Tablet Stand Holder                 6061.77   1511.37
Wool Blend Scarf                    4256.55   1498.41
Desk Organizer Set                  5593.62   1349.77
Tape Dispenser Heavy Duty           3058.89    856.52
Sports Water Bottle 750ml           2930.65    832.21
Silk Tie Collection                 2307.23    667.04
Premium Notebook Set A5             2536.17    665.31
Stapler Full-Size                   2622.15    544.94
Desk Calendar 2025                  2481.21    489.92
Whiteboard Markers Set 8            2090.67    311.95
Ballpoint Pen Pack 12               1760.36    254.45
Binder Clips Assorted 48pc          1924.59    214.49
Sticky Notes Multicolor 6-Pack      1072.27     61.90
Highlighters Neon Pack 6             942.61     -0.37
Paper Clips Box 500pc                901.89    -79.95

##**One Product To Promote is : Ergonomic Office Chair**

In [ ]:
best_product = (
    df.groupby("Product_Name")["Profit"]
      .sum()
      .idxmax()
)

best_product

'Ergonomic Office Chair'

## 📊 Final Business Insights

### ✅ Best Category
The **Furniture** category generated the highest total profit and total sales, making it the best-performing product category. This indicates strong customer demand and high revenue potential within the furniture segment.

### 🌍 Strongest Region
The **Europe** region achieved the highest overall profit, making it the strongest-performing region. This suggests that the company has a strong market presence and customer base in this region.

### 🚀 Product to Promote
The **Ergonomic Office Chair** generated the highest total profit among all products. Promoting this product through targeted marketing campaigns could further increase the company's profitability due to its proven financial performance.

### 💡 Additional Insights
- Office furniture products consistently rank among the top-performing products in both sales and profit.
- Some low-priced office supplies generated very low or even negative profit, indicating that their pricing strategy or operational costs should be reviewed.
- Focusing marketing efforts on high-profit products while optimizing underperforming products can improve overall business performance.